#SET WORKING DIRECTORY TO LOCATION OF THE SOURCE DATA FILE

NYSVOTERS<-read.table(file='AllNYSVoters_20240722.txt',header = FALSE,
                      fill=TRUE, sep = ',')

#Assign field names conatined in BOE documentation
colnames(NYSVOTERS)[1:4]<-c("LASTNAME","FIRSTNAME","MIDDLENAME","NAMESUFFIX")
colnames(NYSVOTERS)[5:15]<-c("RADDNUMBER","RHALFCODE","RPREDIRECTION","RSTREETNAME","RPOSTDIRECTION","RPARTMENTTYPE","RPAPARTMENT","RADDRNONSTD","RCITY","RZIP5","RZIP4")
colnames(NYSVOTERS)[16:19]<-c("MAILADD1","MAILADD2","MAILADD3","MAILADD4")
colnames(NYSVOTERS)[20:21]<-c("DOB","GENDER")
colnames(NYSVOTERS)[22:23]<-c("ENROLLMENT","OTHERPARTY")
colnames(NYSVOTERS)[24:31]<-c("COUNTYCODE","ED","LD","TOWNCITY","WARD","CD","SD","AD")
colnames(NYSVOTERS)[32]<-c("LASTVOTERDATE")
colnames(NYSVOTERS)[33:36]<-c("PREVYEARVOTED","PREVCOUNTY","PREVADDRESS","PREVNAME")
colnames(NYSVOTERS)[37:41]<-c("COUNTYVRNUMBER","REGDATE","VRSOURCE","IDREQUIRED","IDMET")
colnames(NYSVOTERS)[42:45]<-c("STATUS","REASONCODE","INACT_DATE","PURGE_DATE")
colnames(NYSVOTERS)[46]<-c("SBOEID")
colnames(NYSVOTERS)[47]<-c("VoterHistory")

#Add county names and region to dataset
NYSCOUNTIES<-read.table(file='NYS_CountyName_Region.csv',header=TRUE,sep=',')
NYSVOTERS<-merge(NYSVOTERS,NYSCOUNTIES,by="COUNTYCODE")

#Create single field for registered party
NYSVOTERS$PARTY[NYSVOTERS$ENROLLMENT=="BLK"]<-"BLK"
NYSVOTERS$PARTY[NYSVOTERS$ENROLLMENT=="CON"]<-"CON"
NYSVOTERS$PARTY[NYSVOTERS$ENROLLMENT=="DEM"]<-"DEM"
NYSVOTERS$PARTY[NYSVOTERS$OTHERPARTY == "FDM"]<-"FDM"
NYSVOTERS$PARTY[NYSVOTERS$ENROLLMENT=="GRE" | NYSVOTERS$OTHERPARTY=="Gre" | NYSVOTERS$OTHERPARTY == "GRE"]<-"GRE"
NYSVOTERS$PARTY[NYSVOTERS$ENROLLMENT=="IND" | NYSVOTERS$OTHERPARTY=="Ind" | NYSVOTERS$OTHERPARTY == "IND"]<-"IND"
NYSVOTERS$PARTY[NYSVOTERS$ENROLLMENT=="LBT" | NYSVOTERS$OTHERPARTY=="Lbt" | NYSVOTERS$OTHERPARTY == "LBT"]<-"LBT"
NYSVOTERS$PARTY[NYSVOTERS$OTHERPARTY == "OTH"]<-"OTH"
NYSVOTERS$PARTY[NYSVOTERS$ENROLLMENT=="REF" | NYSVOTERS$OTHERPARTY == "REF"]<-"REF"
NYSVOTERS$PARTY[NYSVOTERS$ENROLLMENT=="REP" | NYSVOTERS$ENROLLMENT=="Rep"]<-"REP"
NYSVOTERS$PARTY[NYSVOTERS$OTHERPARTY == "RTH"]<-"RTH"
NYSVOTERS$PARTY[NYSVOTERS$ENROLLMENT=="SAM" | NYSVOTERS$OTHERPARTY == "SAM"]<-"SAM"
NYSVOTERS$PARTY[NYSVOTERS$OTHERPARTY == "SWP"]<-"SWP"
NYSVOTERS$PARTY[NYSVOTERS$ENROLLMENT=="WEP" | NYSVOTERS$OTHERPARTY == "WEP"]<-"WEP"
NYSVOTERS$PARTY[NYSVOTERS$ENROLLMENT=="WOR"]<-"WOR"

#Confirm whether file contains non-active voters
#Keep only active voters
table(NYSVOTERS$STATUS)
NYSVOTERS<-subset(NYSVOTERS,
      NYSVOTERS$STATUS %in% c("A", "AF", "AM", "AP", "AU"))

#Produce tables summarizing data
table(NYSVOTERS$REGION,NYSVOTERS$PARTY)
table(NYSVOTERS$COUNTYNAME)
table(NYSVOTERS$CD, NYSVOTERS$PARTY)

#Produce output for future use
write.csv(NYSVOTERS, file="NYS_Voters_Jul24.csv")
save(NYSVOTERS, file="NYS_Voters_Jul24.RData")
